version: '2'

volumes:
  static: {}
  caddy: {}
  media: {}

services:
  django-a:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"

  django-b:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "400m"
        max-file: "5"

  postgres:
    build: ./compose/postgres
    volumes:
      - /data/djangopackages/postgres:/var/lib/postgresql/data
      - /data/djangopackages/backups:/backups
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "600m"
        max-file: "5"

  caddy:
    build: ./compose/caddy
    depends_on:
      - django-a
      - django-b
    volumes:
      - static:/data/static
      - media:/data/media
      - caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "600m"
        max-file: "5"

  redis:
    build: ./compose/redis
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

